### ISSUE TITLE
Initial Implementation

### ISSUE THREAD

**Issue by MoonMoon1919** [cloudposse/terraform-aws-ec2-autoscale-group#1]
My general thoughts are that it should include the following resources:
- launch config
- autoscaling group
- security group
- dns record
- iam instance profile
- iam role
- elb (w/ variable for enabled)
- eip (w/ variable for enabled)

Variables:
- min/max size
- enabled
- volume size
- vpc id
- user data script var (this would need to be a path using ${path.module} syntax in local module)
- elb enabled/disabled
- eip enabled/disabled
- dns zone id
- security groups

**Comment by osterman** [comment]
Resources sound good, except for not sure how we can leverage the DNS record with an ASG?

We should also define the outputs. I think they would be

## outputs

* `security_group_id`

## variables
* `instance_type`
* `namespace`, `stage`, `name`, `attributes`, `delimiter` - for label module
* `subnet_ids`
* `ssh_key_pair`

## references
Refer to these modules/variables for inspiration:
- <https://github.com/cloudposse/terraform-aws-ec2-instance-group/blob/master/variables.tf>
- <https://github.com/cloudposse/terraform-aws-ec2-instance/blob/master/variables.tf>

**Comment by MoonMoon1919** [comment]
That sounds good. I like that.

I was thinking the DNS record would be used only if enabled and an ELB and EIP was requested. Thoughts?

**Comment by osterman** [comment]
I think the ALB belongs outside of this module for greatest flexibility. 

Check these out: 
- <https://github.com/cloudposse/terraform-aws-alb-ingress>
- <https://github.com/cloudposse/terraform-aws-alb>
- <https://github.com/cloudposse/terraform-aws-alb-target-group-cloudwatch-sns-alarms>

Perhaps the module can create the target groups ARNs. Then you can use the `alb-ingress` module to route traffic to that ARN.

https://www.terraform.io/docs/providers/aws/r/autoscaling_attachment.html

**Comment by MoonMoon1919** [comment]
I like that, sounds good!
