### ISSUE TITLE
Use non deprecated tag keys PR causes bug

### ISSUE THREAD

**Issue by linhkikuchi** [cloudposse/terraform-aws-ec2-autoscale-group#100]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Existing ASG with tags have this error `The argument "tag.4.value" is required, but no definition was found.` after upgrading to version `0.31.1`. Can only do terraform apply if tags are removed. 
(Changes from this PR https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/95)

## Expected Behavior
Expected existing resources to have no change when upgrading from `0.31.0` to `0.31.1`

## Steps to Reproduce
1. Create ASG resources from module `cloudposse/ec2-autoscale-group/aws` version `0.31.0`
2. Updating module version to `0.31.1`
3. Run `terraform plan`
```
Error: Missing required argument
│ 
│   with module.go_translate.module.autoscale_group.aws_autoscaling_group.default[0],
│   on .terraform/modules/go_translate.autoscale_group/main.tf line 144, in resource "aws_autoscaling_group" "default":
│  144: resource "aws_autoscaling_group" "default" {
│ 
│ The argument "tag.4.value" is required, but no definition was found.
╵
```

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc] OSX
 - Version [e.g. 10.15] 12.2

**Comment by nitrocode** [comment]
How could this be fixed by the terraform?

If it cannot be fixed, is it better to document the path you described in order to upgrade from the old version to the new version?

**Comment by linhkikuchi** [comment]
> How could this be fixed by the terraform?
> 
> If it cannot be fixed, is it better to document the path you described in order to upgrade from the old version to the new version?

This can be fixed by remove empty/null values from tags https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/101/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR142-R145

**Comment by linhkikuchi** [comment]
Fixed by https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/101
