### ISSUE TITLE
Support AWS provider 3.x

### ISSUE THREAD

**Issue by abeluck** [cloudposse/terraform-aws-ec2-autoscale-group#33]
## Describe the Feature

AWS Provider 3.x has been released. 

## Expected Behavior

This module supports the new provider version.

[Terraform AWS Provider Version 3 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade)

**Comment by dotCipher** [comment]
@abeluck @SweetOps this should probably be closed now that it's fixed
