### ISSUE TITLE
Scaling policy type does not support all its possible values

### ISSUE THREAD

**Issue by james64** [cloudposse/terraform-aws-ec2-autoscale-group#55]
## Describe the Bug
Module has variables [scale_up_policy_type](https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/master/variables.tf#L323) and [scale_down_policy_type](https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/master/variables.tf#L347). According to documentation they support all values allowed in [autoscaling_policy tf resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy#policy_type) namely `SimpleScaling`, `StepScaling` and `TargetTrackingScaling`. On the other hand [implementation of scaling policies](https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/master/autoscaling.tf#L7) does not contain blocks [step_adjustments](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy#step_adjustment) and [target_tracking_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy#target_tracking_configuration) which are necessary to use `StepScaling` or `TargetTrackingScaling` respectively. This means that effectively only `SimpleScaling` is available.

## Expected Behavior
Option A - support `SimpleScaling`
* Drop variables `scale_*_policy_type` and replace them with hardcoded `SimpleScaling`
* Explicit description of this in readme

Option B - full support for all three policies

**Comment by nitrocode** [comment]
That makes sense.

Option B makes the most sense to me. If you have some free time, please feel free to contribute :pray:

**Comment by Nuru** [comment]
@james64 Thank you for bringing this to our attention.

For now, we are going to document that only `SimpleScaling` is supported, but we will leave the variables (with default values) to leave room for future enhancements and to not break existing modules that set them. 

We will accept a PR that adds support for the other scaling types if it includes examples of them in the `examples/complete` test.
