### ISSUE TITLE
desired_capacity should be optional

### ISSUE THREAD

**Issue by ByJacob** [cloudposse/terraform-aws-ec2-autoscale-group#66]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
When the automatic scaling increases the number of instances and we execute the code from desired_capacity, the number of instances will be set according to the value of desired_capacity, ignoring the current alarm state. If we do not specify desired_capacity, it will be set to the minimum value anyway.

## Expected Behavior
When the current number of instances is 2 and we execute the code without desired_capacity , 2 instances will still work.

## Steps to Reproduce
1. Setup ASG with alarm
2. Trigger allarb (now asg should have 2 insatnce)
3. Apply changes (example change ami)

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: linux
 - Version 0.22.0

## Additional Context
https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/master/main.tf#L141

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#desired_capacity

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#waiting-for-capacity

**Comment by Nuru** [comment]
Closed by #67
