### ISSUE TITLE
Remove deprecated provider `hashicorp/template`

### ISSUE THREAD

**Issue by DamianBudelewski** [cloudposse/terraform-aws-ec2-autoscale-group#80]
## Describe the Bug

I got the error attached below in the logs section, when using this module because it requires `hashicorp/template`. I checked and it doesn't seem like you use it anymore. 

## Expected Behavior
Initializing the module without any errors.

## Steps to Reproduce
1. Create the file with the module at its newest version using the darwin_arm64 platform.
2. Try to run `terraform init`.

## Logs

```
Error: Incompatible provider version
Provider registry.terraform.io/hashicorp/template v2.2.0 does not
have a package available for your current platform, darwin_arm64.
```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: macOS Big Sur
 - Version: 11.6

**Comment by korenyoni** [comment]
@DamianBudelewski 

Thank you for pointing this out. You're right, `tflint --module --enable-rule=terraform_deprecated_index --enable-rule=terraform_unused_declarations --enable-rule=terraform_documented_outputs --enable-rule=terraform_required_providers --enable-rule=terraform_unused_required_providers` outputs the following:

```bash
2 issue(s) found:

Warning: provider 'template' is declared in required_providers but not used by the module (terraform_unused_required_providers)

  on versions.tf line 9:
   9:     template = {
  10:       source  = "hashicorp/template"
  11:       version = ">= 2.0"
  12:     }

Reference: https://github.com/terraform-linters/tflint/blob/v0.27.0/docs/rules/terraform_unused_required_providers.md

Warning: provider 'null' is declared in required_providers but not used by the module (terraform_unused_required_providers)

  on versions.tf line 13:
  13:     null = {
  14:       source  = "hashicorp/null"
  15:       version = ">= 2.0"
  16:     }

Reference: https://github.com/terraform-linters/tflint/blob/v0.27.0/docs/rules/terraform_unused_required_providers.md

```
