### ISSUE TITLE
Add option to create ECS cluster with ASG

### ISSUE THREAD

**Issue by kevcube** [cloudposse/terraform-aws-ec2-autoscale-group#83]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

I'll be using this module to create an ASG where the instances will be joining an ECS cluster.
It would be nice to have the ability to create a cluster within this module, and if that option is used, then to add to the user_data and join the ECS cluster from there 

## Expected Behavior

A flag `var.create_ecs_cluster` which will then also create an ECS cluster with the same naming as the ASG, and will also add lines to the user_data of the instances in this ASG that joins them to the ECS cluster.

## Alternatives Considered

- I can wrap this module with a parent module that adds the resource for ECS cluster and adds to the user_data.
- I can use a separate module which just creates the single resource ECS cluster.

## Additional Context

I am using Terragrunt so my infrastructure is based on modules, it is somewhat painful to create single resources in my architecture pattern. That's why ideally it could be done in this module.

**Comment by nitrocode** [comment]
Detailed explanation here https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/84#issuecomment-1048388093
