### ISSUE TITLE
launch_template_version is not being used

### ISSUE THREAD

**Issue by martinhanzik** [cloudposse/terraform-aws-ec2-autoscale-group#9]
launch_template_version is not being used anywhere

**Comment by aknysh** [comment]
@martinhanzik  thanks!
Did you mean this https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/master/main.tf#L99?

**Comment by martinhanzik** [comment]
No, I meant this https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/search?q=launch_template_version&unscoped_q=launch_template_version

**Comment by evgmoskalenko** [comment]
The module always deploys with the template version = 1. Even if launch_template has the latest version = 5

~ module.asg.aws_launch_template.default
      latest_version:                          "5" => "0"
      tag_specifications.0.tags.sourceCodeRef: "0ccb201" => "52e5bb1"
